package internationalization

type CountryData struct {
	CountryName       string
	OfficialStateName string
	Sovereignty       string
	Alpha2Code        string
	Alpha3Code        string
	NumericCode       string
	SubdivisionCode   string
	InternetccTLD     string
	Flag              string
}

var Cultures = []CountryData{
	{
		Alpha2Code:        "AF",
		CountryName:       "Afghanistan",
		OfficialStateName: "The Islamic Republic of Afghanistan",
		NumericCode:       "004",
		InternetccTLD:     ".af",
		Flag:              Flag_Afghanistan,
	},
	{
		Alpha2Code:        "AX",
		CountryName:       "Åland Islands",
		OfficialStateName: "Åland",
		NumericCode:       "248",
		InternetccTLD:     ".ax",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "AL",
		CountryName:       "Albania",
		OfficialStateName: "The Republic of Albania",
		NumericCode:       "008",
		InternetccTLD:     ".al",
		Flag:              Flag_Albania,
	},
	{
		Alpha2Code:        "DZ",
		CountryName:       "Algeria",
		OfficialStateName: "The People&#39;s Democratic Republic of Algeria",
		NumericCode:       "012",
		InternetccTLD:     ".dz",
		Flag:              Flag_Algeria,
	},
	{
		Alpha2Code:        "AS",
		CountryName:       "American Samoa",
		OfficialStateName: "The Territory of American Samoa",
		NumericCode:       "016",
		InternetccTLD:     ".as",
		Flag:              Flag_American_Samoa,
	},
	{
		Alpha2Code:        "AD",
		CountryName:       "Andorra",
		OfficialStateName: "The Principality of Andorra",
		NumericCode:       "020",
		InternetccTLD:     ".ad",
		Flag:              Flag_Andorra,
	},
	{
		Alpha2Code:        "AO",
		CountryName:       "Angola",
		OfficialStateName: "The Republic of Angola",
		NumericCode:       "024",
		InternetccTLD:     ".ao",
		Flag:              Flag_Angola,
	},
	{
		Alpha2Code:        "AI",
		CountryName:       "Anguilla",
		OfficialStateName: "Anguilla",
		NumericCode:       "660",
		InternetccTLD:     ".ai",
		Flag:              Flag_Anguilla,
	},
	{
		Alpha2Code:        "AQ",
		CountryName:       "[b]",
		OfficialStateName: "All land and ice shelves south of the ",
		NumericCode:       "010",
		InternetccTLD:     ".aq",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "AG",
		CountryName:       "Antigua and Barbuda",
		OfficialStateName: "Antigua and Barbuda",
		NumericCode:       "028",
		InternetccTLD:     ".ag",
		Flag:              Flag_Antigua_Barbuda,
	},
	{
		Alpha2Code:        "AR",
		CountryName:       "Argentina",
		OfficialStateName: "The Argentine Republic",
		NumericCode:       "032",
		InternetccTLD:     ".ar",
		Flag:              Flag_Argentina,
	},
	{
		Alpha2Code:        "AM",
		CountryName:       "Armenia",
		OfficialStateName: "The Republic of Armenia",
		NumericCode:       "051",
		InternetccTLD:     ".am",
		Flag:              Flag_Armenia,
	},
	{
		Alpha2Code:        "AW",
		CountryName:       "Aruba",
		OfficialStateName: "Aruba",
		NumericCode:       "533",
		InternetccTLD:     ".aw",
		Flag:              Flag_Aruba,
	},
	{
		Alpha2Code:        "AU",
		CountryName:       "Australia",
		OfficialStateName: "The Commonwealth of Australia",
		NumericCode:       "036",
		InternetccTLD:     ".au",
		Flag:              Flag_Australia,
	},
	{
		Alpha2Code:        "AT",
		CountryName:       "Austria",
		OfficialStateName: "The Republic of Austria",
		NumericCode:       "040",
		InternetccTLD:     ".at",
		Flag:              Flag_Austria,
	},
	{
		Alpha2Code:        "AZ",
		CountryName:       "Azerbaijan",
		OfficialStateName: "The Republic of Azerbaijan",
		NumericCode:       "031",
		InternetccTLD:     ".az",
		Flag:              Flag_Azerbaijan,
	},
	{
		Alpha2Code:        "BS",
		CountryName:       "Bahamas (the)",
		OfficialStateName: "The Commonwealth of The Bahamas",
		NumericCode:       "044",
		InternetccTLD:     ".bs",
		Flag:              Flag_Bahamas,
	},
	{
		Alpha2Code:        "BH",
		CountryName:       "Bahrain",
		OfficialStateName: "The Kingdom of Bahrain",
		NumericCode:       "048",
		InternetccTLD:     ".bh",
		Flag:              Flag_Bahrain,
	},
	{
		Alpha2Code:        "BD",
		CountryName:       "Bangladesh",
		OfficialStateName: "The People&#39;s Republic of Bangladesh",
		NumericCode:       "050",
		InternetccTLD:     ".bd",
		Flag:              Flag_Bangladesh,
	},
	{
		Alpha2Code:        "BB",
		CountryName:       "Barbados",
		OfficialStateName: "Barbados",
		NumericCode:       "052",
		InternetccTLD:     ".bb",
		Flag:              Flag_Barbados,
	},
	{
		Alpha2Code:        "BY",
		CountryName:       "Belarus",
		OfficialStateName: "The Republic of Belarus",
		NumericCode:       "112",
		InternetccTLD:     ".by",
		Flag:              Flag_Belarus,
	},
	{
		Alpha2Code:        "BE",
		CountryName:       "Belgium",
		OfficialStateName: "The Kingdom of Belgium",
		NumericCode:       "056",
		InternetccTLD:     ".be",
		Flag:              Flag_Belgium,
	},
	{
		Alpha2Code:        "BZ",
		CountryName:       "Belize",
		OfficialStateName: "Belize",
		NumericCode:       "084",
		InternetccTLD:     ".bz",
		Flag:              Flag_Belize,
	},
	{
		Alpha2Code:        "BJ",
		CountryName:       "Benin",
		OfficialStateName: "The Republic of Benin",
		NumericCode:       "204",
		InternetccTLD:     ".bj",
		Flag:              Flag_Benin,
	},
	{
		Alpha2Code:        "BM",
		CountryName:       "Bermuda",
		OfficialStateName: "Bermuda",
		NumericCode:       "060",
		InternetccTLD:     ".bm",
		Flag:              Flag_Bermuda,
	},
	{
		Alpha2Code:        "BT",
		CountryName:       "Bhutan",
		OfficialStateName: "The Kingdom of Bhutan",
		NumericCode:       "064",
		InternetccTLD:     ".bt",
		Flag:              Flag_Bhutan,
	},
	{
		Alpha2Code:        "BO",
		CountryName:       "Bolivia (Plurinational State of)",
		OfficialStateName: "The Plurinational State of Bolivia",
		NumericCode:       "068",
		InternetccTLD:     ".bo",
		Flag:              Flag_Bolivia,
	},
	{
		Alpha2Code:        "BQ",
		CountryName:       "Saba",
		OfficialStateName: "Bonaire, Sint Eustatius and Saba",
		NumericCode:       "535",
		InternetccTLD:     ".bq",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "BA",
		CountryName:       "Bosnia and Herzegovina",
		OfficialStateName: "Bosnia and Herzegovina",
		NumericCode:       "070",
		InternetccTLD:     ".ba",
		Flag:              Flag_Bosnia_Herzegovina,
	},
	{
		Alpha2Code:        "BW",
		CountryName:       "Botswana",
		OfficialStateName: "The Republic of Botswana",
		NumericCode:       "072",
		InternetccTLD:     ".bw",
		Flag:              Flag_Botswana,
	},
	{
		Alpha2Code:        "BV",
		CountryName:       "Bouvet Island",
		OfficialStateName: "Bouvet Island",
		NumericCode:       "074",
		InternetccTLD:     "[e]",
		Flag:              Flag_Bouvet_Island,
	},
	{
		Alpha2Code:        "BR",
		CountryName:       "Brazil",
		OfficialStateName: "The Federative Republic of Brazil",
		NumericCode:       "076",
		InternetccTLD:     ".br",
		Flag:              Flag_Brazil,
	},
	{
		Alpha2Code:        "IO",
		CountryName:       "British Indian Ocean Territory (the)",
		OfficialStateName: "The British Indian Ocean Territory",
		NumericCode:       "086",
		InternetccTLD:     ".io",
		Flag:              Flag_British_Indian_Ocean_Territory,
	},
	{
		Alpha2Code:        "BN",
		CountryName:       "Brunei",
		OfficialStateName: "The Nation of Brunei, the Abode of Peace",
		NumericCode:       "096",
		InternetccTLD:     ".bn",
		Flag:              Flag_Brunei,
	},
	{
		Alpha2Code:        "BG",
		CountryName:       "Bulgaria",
		OfficialStateName: "The Republic of Bulgaria",
		NumericCode:       "100",
		InternetccTLD:     ".bg",
		Flag:              Flag_Bulgaria,
	},
	{
		Alpha2Code:        "BF",
		CountryName:       "Burkina Faso",
		OfficialStateName: "Burkina Faso",
		NumericCode:       "854",
		InternetccTLD:     ".bf",
		Flag:              Flag_Burkina_Faso,
	},
	{
		Alpha2Code:        "BI",
		CountryName:       "Burundi",
		OfficialStateName: "The Republic of Burundi",
		NumericCode:       "108",
		InternetccTLD:     ".bi",
		Flag:              Flag_Burundi,
	},
	{
		Alpha2Code:        "CV",
		CountryName:       "[g]",
		OfficialStateName: "The Republic of Cabo Verde",
		NumericCode:       "132",
		InternetccTLD:     ".cv",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "KH",
		CountryName:       "Cambodia",
		OfficialStateName: "The Kingdom of Cambodia",
		NumericCode:       "116",
		InternetccTLD:     ".kh",
		Flag:              Flag_Cambodia,
	},
	{
		Alpha2Code:        "CM",
		CountryName:       "Cameroon",
		OfficialStateName: "The Republic of Cameroon",
		NumericCode:       "120",
		InternetccTLD:     ".cm",
		Flag:              Flag_Cameroon,
	},
	{
		Alpha2Code:        "CA",
		CountryName:       "Canada",
		OfficialStateName: "Canada",
		NumericCode:       "124",
		InternetccTLD:     ".ca",
		Flag:              Flag_Canada,
	},
	{
		Alpha2Code:        "KY",
		CountryName:       "Cayman Islands (the)",
		OfficialStateName: "The Cayman Islands",
		NumericCode:       "136",
		InternetccTLD:     ".ky",
		Flag:              Flag_Cayman_Islands,
	},
	{
		Alpha2Code:        "CF",
		CountryName:       "Central African Republic (the)",
		OfficialStateName: "The Central African Republic",
		NumericCode:       "140",
		InternetccTLD:     ".cf",
		Flag:              Flag_Central_African_Republic,
	},
	{
		Alpha2Code:        "TD",
		CountryName:       "Chad",
		OfficialStateName: "The Republic of Chad",
		NumericCode:       "148",
		InternetccTLD:     ".td",
		Flag:              Flag_Chad,
	},
	{
		Alpha2Code:        "CL",
		CountryName:       "Chile",
		OfficialStateName: "The Republic of Chile",
		NumericCode:       "152",
		InternetccTLD:     ".cl",
		Flag:              Flag_Chile,
	},
	{
		Alpha2Code:        "CN",
		CountryName:       "China",
		OfficialStateName: "The People&#39;s Republic of China",
		NumericCode:       "156",
		InternetccTLD:     ".cn",
		Flag:              Flag_China,
	},
	{
		Alpha2Code:        "CX",
		CountryName:       "Christmas Island",
		OfficialStateName: "The Territory of Christmas Island",
		NumericCode:       "162",
		InternetccTLD:     ".cx",
		Flag:              Flag_Christmas_Island,
	},
	{
		Alpha2Code:        "CC",
		CountryName:       "Cocos (Keeling) Islands (the)",
		OfficialStateName: "The Territory of Cocos (Keeling) Islands",
		NumericCode:       "166",
		InternetccTLD:     ".cc",
		Flag:              Flag_Cocos_Keeling_Islands,
	},
	{
		Alpha2Code:        "CO",
		CountryName:       "Colombia",
		OfficialStateName: "The Republic of Colombia",
		NumericCode:       "170",
		InternetccTLD:     ".co",
		Flag:              Flag_Colombia,
	},
	{
		Alpha2Code:        "KM",
		CountryName:       "Comoros (the)",
		OfficialStateName: "The Union of the Comoros",
		NumericCode:       "174",
		InternetccTLD:     ".km",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "CD",
		CountryName:       "Congo (the Democratic Republic of the)",
		OfficialStateName: "The Democratic Republic of the Congo",
		NumericCode:       "180",
		InternetccTLD:     ".cd",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "CG",
		CountryName:       "[h]",
		OfficialStateName: "The Republic of the Congo",
		NumericCode:       "178",
		InternetccTLD:     ".cg",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "CK",
		CountryName:       "Cook Islands (the)",
		OfficialStateName: "The Cook Islands",
		NumericCode:       "184",
		InternetccTLD:     ".ck",
		Flag:              Flag_Cook_Islands,
	},
	{
		Alpha2Code:        "CR",
		CountryName:       "Costa Rica",
		OfficialStateName: "The Republic of Costa Rica",
		NumericCode:       "188",
		InternetccTLD:     ".cr",
		Flag:              Flag_Costa_Rica,
	},
	{
		Alpha2Code:        "CI",
		CountryName:       "Cote d'Ivoire",
		OfficialStateName: "The Republic of Côte d'Ivoire",
		NumericCode:       "384",
		InternetccTLD:     ".ci",
		Flag:              Flag_Cote_DIvoire,
	},
	{
		Alpha2Code:        "HR",
		CountryName:       "Croatia",
		OfficialStateName: "The Republic of Croatia",
		NumericCode:       "191",
		InternetccTLD:     ".hr",
		Flag:              Flag_Croatia,
	},
	{
		Alpha2Code:        "CU",
		CountryName:       "Cuba",
		OfficialStateName: "The Republic of Cuba",
		NumericCode:       "192",
		InternetccTLD:     ".cu",
		Flag:              Flag_Cuba,
	},
	{
		Alpha2Code:        "CW",
		CountryName:       "Curaçao",
		OfficialStateName: "The Country of Curaçao",
		NumericCode:       "531",
		InternetccTLD:     ".cw",
		Flag:              Flag_Curaçao,
	},
	{
		Alpha2Code:        "CY",
		CountryName:       "Cyprus",
		OfficialStateName: "The Republic of Cyprus",
		NumericCode:       "196",
		InternetccTLD:     ".cy",
		Flag:              Flag_Cyprus,
	},
	{
		Alpha2Code:        "CZ",
		CountryName:       "Czechia",
		OfficialStateName: "The Czech Republic",
		NumericCode:       "203",
		InternetccTLD:     ".cz",
		Flag:              Flag_Czechia,
	},
	{
		Alpha2Code:        "DK",
		CountryName:       "Denmark",
		OfficialStateName: "The Kingdom of Denmark",
		NumericCode:       "208",
		InternetccTLD:     ".dk",
		Flag:              Flag_Denmark,
	},
	{
		Alpha2Code:        "DJ",
		CountryName:       "Djibouti",
		OfficialStateName: "The Republic of Djibouti",
		NumericCode:       "262",
		InternetccTLD:     ".dj",
		Flag:              Flag_Djibouti,
	},
	{
		Alpha2Code:        "DM",
		CountryName:       "Dominica",
		OfficialStateName: "The Commonwealth of Dominica",
		NumericCode:       "212",
		InternetccTLD:     ".dm",
		Flag:              Flag_Dominica,
	},
	{
		Alpha2Code:        "DO",
		CountryName:       "Dominican Republic (the)",
		OfficialStateName: "The Dominican Republic",
		NumericCode:       "214",
		InternetccTLD:     ".do",
		Flag:              Flag_Dominican_Republic,
	},
	{
		Alpha2Code:        "EC",
		CountryName:       "Ecuador",
		OfficialStateName: "The Republic of Ecuador",
		NumericCode:       "218",
		InternetccTLD:     ".ec",
		Flag:              Flag_Ecuador,
	},
	{
		Alpha2Code:        "EG",
		CountryName:       "Egypt",
		OfficialStateName: "The Arab Republic of Egypt",
		NumericCode:       "818",
		InternetccTLD:     ".eg",
		Flag:              Flag_Egypt,
	},
	{
		Alpha2Code:        "SV",
		CountryName:       "El Salvador",
		OfficialStateName: "The Republic of El Salvador",
		NumericCode:       "222",
		InternetccTLD:     ".sv",
		Flag:              Flag_El_Salvador,
	},
	{
		Alpha2Code:        "GQ",
		CountryName:       "Equatorial Guinea",
		OfficialStateName: "The Republic of Equatorial Guinea",
		NumericCode:       "226",
		InternetccTLD:     ".gq",
		Flag:              Flag_Equatorial_Guinea,
	},
	{
		Alpha2Code:        "ER",
		CountryName:       "Eritrea",
		OfficialStateName: "The State of Eritrea",
		NumericCode:       "232",
		InternetccTLD:     ".er",
		Flag:              Flag_Eritrea,
	},
	{
		Alpha2Code:        "EE",
		CountryName:       "Estonia",
		OfficialStateName: "The Republic of Estonia",
		NumericCode:       "233",
		InternetccTLD:     ".ee",
		Flag:              Flag_Estonia,
	},
	{
		Alpha2Code:        "SZ",
		CountryName:       "Eswatini",
		OfficialStateName: "The Kingdom of Eswatini",
		NumericCode:       "748",
		InternetccTLD:     ".sz",
		Flag:              Flag_Eswatini,
	},
	{
		Alpha2Code:        "ET",
		CountryName:       "Ethiopia",
		OfficialStateName: "The Federal Democratic Republic of Ethiopia",
		NumericCode:       "231",
		InternetccTLD:     ".et",
		Flag:              Flag_Ethiopia,
	},
	{
		Alpha2Code:        "FK",
		CountryName:       "Falkland Islands",
		OfficialStateName: "The Falkland Islands",
		NumericCode:       "238",
		InternetccTLD:     ".fk",
		Flag:              Flag_Falkland_Islands,
	},
	{
		Alpha2Code:        "FO",
		CountryName:       "Faroe Islands (the)",
		OfficialStateName: "The Faroe Islands",
		NumericCode:       "234",
		InternetccTLD:     ".fo",
		Flag:              Flag_Faroe_Islands,
	},
	{
		Alpha2Code:        "FJ",
		CountryName:       "Fiji",
		OfficialStateName: "The Republic of Fiji",
		NumericCode:       "242",
		InternetccTLD:     ".fj",
		Flag:              Flag_Fiji,
	},
	{
		Alpha2Code:        "FI",
		CountryName:       "Finland",
		OfficialStateName: "The Republic of Finland",
		NumericCode:       "246",
		InternetccTLD:     ".fi",
		Flag:              Flag_Finland,
	},
	{
		Alpha2Code:        "FR",
		CountryName:       "France",
		OfficialStateName: "The French Republic",
		NumericCode:       "250",
		InternetccTLD:     ".fr",
		Flag:              Flag_France,
	},
	{
		Alpha2Code:        "GF",
		CountryName:       "French Guiana",
		OfficialStateName: "Guyane",
		NumericCode:       "254",
		InternetccTLD:     ".gf",
		Flag:              Flag_French_Guiana,
	},
	{
		Alpha2Code:        "PF",
		CountryName:       "French Polynesia",
		OfficialStateName: "French Polynesia",
		NumericCode:       "258",
		InternetccTLD:     ".pf",
		Flag:              Flag_French_Polynesia,
	},
	{
		Alpha2Code:        "TF",
		CountryName:       "[n]",
		OfficialStateName: "The French Southern and Antarctic Lands",
		NumericCode:       "260",
		InternetccTLD:     ".tf",
		Flag:              Flag_French_Southern_Territories, // ?
	},
	{
		Alpha2Code:        "GA",
		CountryName:       "Gabon",
		OfficialStateName: "The Gabonese Republic",
		NumericCode:       "266",
		InternetccTLD:     ".ga",
		Flag:              Flag_Gabon,
	},
	{
		Alpha2Code:        "GM",
		CountryName:       "Gambia (the)",
		OfficialStateName: "The Republic of The Gambia",
		NumericCode:       "270",
		InternetccTLD:     ".gm",
		Flag:              Flag_Gambia,
	},
	{
		Alpha2Code:        "GE",
		CountryName:       "Georgia",
		OfficialStateName: "Georgia",
		NumericCode:       "268",
		InternetccTLD:     ".ge",
		Flag:              Flag_Georgia,
	},
	{
		Alpha2Code:        "DE",
		CountryName:       "Germany",
		OfficialStateName: "The Federal Republic of Germany",
		NumericCode:       "276",
		InternetccTLD:     ".de",
		Flag:              Flag_Germany,
	},
	{
		Alpha2Code:        "GH",
		CountryName:       "Ghana",
		OfficialStateName: "The Republic of Ghana",
		NumericCode:       "288",
		InternetccTLD:     ".gh",
		Flag:              Flag_Ghana,
	},
	{
		Alpha2Code:        "GI",
		CountryName:       "Gibraltar",
		OfficialStateName: "Gibraltar",
		NumericCode:       "292",
		InternetccTLD:     ".gi",
		Flag:              Flag_Gibraltar,
	},
	{
		Alpha2Code:        "GR",
		CountryName:       "Greece",
		OfficialStateName: "The Hellenic Republic",
		NumericCode:       "300",
		InternetccTLD:     ".gr",
		Flag:              Flag_Greece,
	},
	{
		Alpha2Code:        "GL",
		CountryName:       "Greenland",
		OfficialStateName: "Kalaallit Nunaat",
		NumericCode:       "304",
		InternetccTLD:     ".gl",
		Flag:              Flag_Greenland,
	},
	{
		Alpha2Code:        "GD",
		CountryName:       "Grenada",
		OfficialStateName: "Grenada",
		NumericCode:       "308",
		InternetccTLD:     ".gd",
		Flag:              Flag_Grenada,
	},
	{
		Alpha2Code:        "GP",
		CountryName:       "Guadeloupe",
		OfficialStateName: "Guadeloupe",
		NumericCode:       "312",
		InternetccTLD:     ".gp",
		Flag:              Flag_Guadeloupe,
	},
	{
		Alpha2Code:        "GU",
		CountryName:       "Guam",
		OfficialStateName: "The Territory of Guam",
		NumericCode:       "316",
		InternetccTLD:     ".gu",
		Flag:              Flag_Guam,
	},
	{
		Alpha2Code:        "GT",
		CountryName:       "Guatemala",
		OfficialStateName: "The Republic of Guatemala",
		NumericCode:       "320",
		InternetccTLD:     ".gt",
		Flag:              Flag_Guatemala,
	},
	{
		Alpha2Code:        "GG",
		CountryName:       "Guernsey",
		OfficialStateName: "The Bailiwick of Guernsey",
		NumericCode:       "831",
		InternetccTLD:     ".gg",
		Flag:              Flag_Guernsey,
	},
	{
		Alpha2Code:        "GN",
		CountryName:       "Guinea",
		OfficialStateName: "The Republic of Guinea",
		NumericCode:       "324",
		InternetccTLD:     ".gn",
		Flag:              Flag_Guinea,
	},
	{
		Alpha2Code:        "GW",
		CountryName:       "Guinea-Bissau",
		OfficialStateName: "The Republic of Guinea-Bissau",
		NumericCode:       "624",
		InternetccTLD:     ".gw",
		Flag:              Flag_Guinea_Bissau,
	},
	{
		Alpha2Code:        "GY",
		CountryName:       "Guyana",
		OfficialStateName: "The Co-operative Republic of Guyana",
		NumericCode:       "328",
		InternetccTLD:     ".gy",
		Flag:              Flag_Guyana,
	},
	{
		Alpha2Code:        "HT",
		CountryName:       "Haiti",
		OfficialStateName: "The Republic of Haiti",
		NumericCode:       "332",
		InternetccTLD:     ".ht",
		Flag:              Flag_Haiti,
	},
	{
		Alpha2Code:        "HM",
		CountryName:       "Heard Island and McDonald Islands",
		OfficialStateName: "The Territory of Heard Island and McDonald Islands",
		NumericCode:       "334",
		InternetccTLD:     ".hm",
		Flag:              Flag_Heard_McDonald_Islands,
	},
	{
		Alpha2Code:        "VA",
		CountryName:       "Vatican",
		OfficialStateName: "The Holy See",
		NumericCode:       "336",
		InternetccTLD:     ".va",
		Flag:              Flag_Vatican_City,
	},
	{
		Alpha2Code:        "HN",
		CountryName:       "Honduras",
		OfficialStateName: "The Republic of Honduras",
		NumericCode:       "340",
		InternetccTLD:     ".hn",
		Flag:              Flag_Honduras,
	},
	{
		Alpha2Code:        "HK",
		CountryName:       "Hong Kong",
		OfficialStateName: "The Hong Kong Special Administrative Region of China",
		NumericCode:       "344",
		InternetccTLD:     ".hk",
		Flag:              Flag_Hong_Kong_SAR_China,
	},
	{
		Alpha2Code:        "HU",
		CountryName:       "Hungary",
		OfficialStateName: "Hungary",
		NumericCode:       "348",
		InternetccTLD:     ".hu",
		Flag:              Flag_Hungary,
	},
	{
		Alpha2Code:        "IS",
		CountryName:       "Iceland",
		OfficialStateName: "Iceland",
		NumericCode:       "352",
		InternetccTLD:     ".is",
		Flag:              Flag_Iceland,
	},
	{
		Alpha2Code:        "IN",
		CountryName:       "India",
		OfficialStateName: "The Republic of India",
		NumericCode:       "356",
		InternetccTLD:     ".in",
		Flag:              Flag_India,
	},
	{
		Alpha2Code:        "ID",
		CountryName:       "Indonesia",
		OfficialStateName: "The Republic of Indonesia",
		NumericCode:       "360",
		InternetccTLD:     ".id",
		Flag:              Flag_Indonesia,
	},
	{
		Alpha2Code:        "IR",
		CountryName:       "Iran (Islamic Republic of)",
		OfficialStateName: "The Islamic Republic of Iran",
		NumericCode:       "364",
		InternetccTLD:     ".ir",
		Flag:              Flag_Iran,
	},
	{
		Alpha2Code:        "IQ",
		CountryName:       "Iraq",
		OfficialStateName: "The Republic of Iraq",
		NumericCode:       "368",
		InternetccTLD:     ".iq",
		Flag:              Flag_Iraq,
	},
	{
		Alpha2Code:        "IE",
		CountryName:       "Ireland",
		OfficialStateName: "Ireland",
		NumericCode:       "372",
		InternetccTLD:     ".ie",
		Flag:              Flag_Ireland,
	},
	{
		Alpha2Code:        "IM",
		CountryName:       "Isle of Man",
		OfficialStateName: "The Isle of Man",
		NumericCode:       "833",
		InternetccTLD:     ".im",
		Flag:              Flag_Isle_of_Man,
	},
	{
		Alpha2Code:        "IL",
		CountryName:       "Israel",
		OfficialStateName: "The State of Israel",
		NumericCode:       "376",
		InternetccTLD:     ".il",
		Flag:              Flag_Israel,
	},
	{
		Alpha2Code:        "IT",
		CountryName:       "Italy",
		OfficialStateName: "The Italian Republic",
		NumericCode:       "380",
		InternetccTLD:     ".it",
		Flag:              Flag_Italy,
	},
	{
		Alpha2Code:        "JM",
		CountryName:       "Jamaica",
		OfficialStateName: "Jamaica",
		NumericCode:       "388",
		InternetccTLD:     ".jm",
		Flag:              Flag_Jamaica,
	},
	{
		Alpha2Code:        "JP",
		CountryName:       "Japan",
		OfficialStateName: "Japan",
		NumericCode:       "392",
		InternetccTLD:     ".jp",
		Flag:              Flag_Japan,
	},
	{
		Alpha2Code:        "JE",
		CountryName:       "Jersey",
		OfficialStateName: "The Bailiwick of Jersey",
		NumericCode:       "832",
		InternetccTLD:     ".je",
		Flag:              Flag_Jersey,
	},
	{
		Alpha2Code:        "JO",
		CountryName:       "Jordan",
		OfficialStateName: "The Hashemite Kingdom of Jordan",
		NumericCode:       "400",
		InternetccTLD:     ".jo",
		Flag:              Flag_Jordan,
	},
	{
		Alpha2Code:        "KZ",
		CountryName:       "Kazakhstan",
		OfficialStateName: "The Republic of Kazakhstan",
		NumericCode:       "398",
		InternetccTLD:     ".kz",
		Flag:              Flag_Kazakhstan,
	},
	{
		Alpha2Code:        "KE",
		CountryName:       "Kenya",
		OfficialStateName: "The Republic of Kenya",
		NumericCode:       "404",
		InternetccTLD:     ".ke",
		Flag:              Flag_Kenya,
	},
	{
		Alpha2Code:        "KI",
		CountryName:       "Kiribati",
		OfficialStateName: "The Republic of Kiribati",
		NumericCode:       "296",
		InternetccTLD:     ".ki",
		Flag:              Flag_Kiribati,
	},
	{
		Alpha2Code:        "KP",
		CountryName:       "North Korea",
		OfficialStateName: "The Democratic People's Republic of Korea",
		NumericCode:       "408",
		InternetccTLD:     ".kp",
		Flag:              Flag_North_Korea,
	},
	{
		Alpha2Code:        "KR",
		CountryName:       "South Korea",
		OfficialStateName: "The Republic of Korea",
		NumericCode:       "410",
		InternetccTLD:     ".kr",
		Flag:              Flag_South_Korea,
	},
	{
		Alpha2Code:        "KW",
		CountryName:       "Kuwait",
		OfficialStateName: "The State of Kuwait",
		NumericCode:       "414",
		InternetccTLD:     ".kw",
		Flag:              Flag_Kuwait,
	},
	{
		Alpha2Code:        "KG",
		CountryName:       "Kyrgyzstan",
		OfficialStateName: "The Kyrgyz Republic",
		NumericCode:       "417",
		InternetccTLD:     ".kg",
		Flag:              Flag_Kyrgyzstan,
	},
	{
		Alpha2Code:        "LA",
		CountryName:       "Laos",
		OfficialStateName: "The Lao People's Democratic Republic",
		NumericCode:       "418",
		InternetccTLD:     ".la",
		Flag:              Flag_Laos,
	},
	{
		Alpha2Code:        "LV",
		CountryName:       "Latvia",
		OfficialStateName: "The Republic of Latvia",
		NumericCode:       "428",
		InternetccTLD:     ".lv",
		Flag:              Flag_Latvia,
	},
	{
		Alpha2Code:        "LB",
		CountryName:       "Lebanon",
		OfficialStateName: "The Lebanese Republic",
		NumericCode:       "422",
		InternetccTLD:     ".lb",
		Flag:              Flag_Lebanon,
	},
	{
		Alpha2Code:        "LS",
		CountryName:       "Lesotho",
		OfficialStateName: "The Kingdom of Lesotho",
		NumericCode:       "426",
		InternetccTLD:     ".ls",
		Flag:              Flag_Lesotho,
	},
	{
		Alpha2Code:        "LR",
		CountryName:       "Liberia",
		OfficialStateName: "The Republic of Liberia",
		NumericCode:       "430",
		InternetccTLD:     ".lr",
		Flag:              Flag_Liberia,
	},
	{
		Alpha2Code:        "LY",
		CountryName:       "Libya",
		OfficialStateName: "The State of Libya",
		NumericCode:       "434",
		InternetccTLD:     ".ly",
		Flag:              Flag_Libya,
	},
	{
		Alpha2Code:        "LI",
		CountryName:       "Liechtenstein",
		OfficialStateName: "The Principality of Liechtenstein",
		NumericCode:       "438",
		InternetccTLD:     ".li",
		Flag:              Flag_Liechtenstein,
	},
	{
		Alpha2Code:        "LT",
		CountryName:       "Lithuania",
		OfficialStateName: "The Republic of Lithuania",
		NumericCode:       "440",
		InternetccTLD:     ".lt",
		Flag:              Flag_Lithuania,
	},
	{
		Alpha2Code:        "LU",
		CountryName:       "Luxembourg",
		OfficialStateName: "The Grand Duchy of Luxembourg",
		NumericCode:       "442",
		InternetccTLD:     ".lu",
		Flag:              Flag_Luxembourg,
	},
	{
		Alpha2Code:        "MO",
		CountryName:       "Macao",
		OfficialStateName: "The Macao Special Administrative Region of China",
		NumericCode:       "446",
		InternetccTLD:     ".mo",
		Flag:              Flag_Macao_Sar_China,
	},
	{
		Alpha2Code:        "MK",
		CountryName:       "North Macedonia",
		OfficialStateName: "The Republic of North Macedonia",
		NumericCode:       "807",
		InternetccTLD:     ".mk",
		Flag:              Flag_North_Macedonia,
	},
	{
		Alpha2Code:        "MG",
		CountryName:       "Madagascar",
		OfficialStateName: "The Republic of Madagascar",
		NumericCode:       "450",
		InternetccTLD:     ".mg",
		Flag:              Flag_Madagascar,
	},
	{
		Alpha2Code:        "MW",
		CountryName:       "Malawi",
		OfficialStateName: "The Republic of Malawi",
		NumericCode:       "454",
		InternetccTLD:     ".mw",
		Flag:              Flag_Malawi,
	},
	{
		Alpha2Code:        "MY",
		CountryName:       "Malaysia",
		OfficialStateName: "Malaysia",
		NumericCode:       "458",
		InternetccTLD:     ".my",
		Flag:              Flag_Malaysia,
	},
	{
		Alpha2Code:        "MV",
		CountryName:       "Maldives",
		OfficialStateName: "The Republic of Maldives",
		NumericCode:       "462",
		InternetccTLD:     ".mv",
		Flag:              Flag_Maldives,
	},
	{
		Alpha2Code:        "ML",
		CountryName:       "Mali",
		OfficialStateName: "The Republic of Mali",
		NumericCode:       "466",
		InternetccTLD:     ".ml",
		Flag:              Flag_Mali,
	},
	{
		Alpha2Code:        "MT",
		CountryName:       "Malta",
		OfficialStateName: "The Republic of Malta",
		NumericCode:       "470",
		InternetccTLD:     ".mt",
		Flag:              Flag_Malta,
	},
	{
		Alpha2Code:        "MH",
		CountryName:       "Marshall Islands (the)",
		OfficialStateName: "The Republic of the Marshall Islands",
		NumericCode:       "584",
		InternetccTLD:     ".mh",
		Flag:              Flag_Marshall_Islands,
	},
	{
		Alpha2Code:        "MQ",
		CountryName:       "Martinique",
		OfficialStateName: "Martinique",
		NumericCode:       "474",
		InternetccTLD:     ".mq",
		Flag:              Flag_Martinique,
	},
	{
		Alpha2Code:        "MR",
		CountryName:       "Mauritania",
		OfficialStateName: "The Islamic Republic of Mauritania",
		NumericCode:       "478",
		InternetccTLD:     ".mr",
		Flag:              Flag_Mauritania,
	},
	{
		Alpha2Code:        "MU",
		CountryName:       "Mauritius",
		OfficialStateName: "The Republic of Mauritius",
		NumericCode:       "480",
		InternetccTLD:     ".mu",
		Flag:              Flag_Mauritius,
	},
	{
		Alpha2Code:        "YT",
		CountryName:       "Mayotte",
		OfficialStateName: "The Department of Mayotte",
		NumericCode:       "175",
		InternetccTLD:     ".yt",
		Flag:              Flag_Mayotte,
	},
	{
		Alpha2Code:        "MX",
		CountryName:       "Mexico",
		OfficialStateName: "The United Mexican States",
		NumericCode:       "484",
		InternetccTLD:     ".mx",
		Flag:              Flag_Mexico,
	},
	{
		Alpha2Code:        "FM",
		CountryName:       "Micronesia (Federated States of)",
		OfficialStateName: "The Federated States of Micronesia",
		NumericCode:       "583",
		InternetccTLD:     ".fm",
		Flag:              Flag_Micronesia,
	},
	{
		Alpha2Code:        "MD",
		CountryName:       "Moldova (the Republic of)",
		OfficialStateName: "The Republic of Moldova",
		NumericCode:       "498",
		InternetccTLD:     ".md",
		Flag:              Flag_Moldova,
	},
	{
		Alpha2Code:        "MC",
		CountryName:       "Monaco",
		OfficialStateName: "The Principality of Monaco",
		NumericCode:       "492",
		InternetccTLD:     ".mc",
		Flag:              Flag_Monaco,
	},
	{
		Alpha2Code:        "MN",
		CountryName:       "Mongolia",
		OfficialStateName: "Mongolia",
		NumericCode:       "496",
		InternetccTLD:     ".mn",
		Flag:              Flag_Mongolia,
	},
	{
		Alpha2Code:        "ME",
		CountryName:       "Montenegro",
		OfficialStateName: "Montenegro",
		NumericCode:       "499",
		InternetccTLD:     ".me",
		Flag:              Flag_Montenegro,
	},
	{
		Alpha2Code:        "MS",
		CountryName:       "Montserrat",
		OfficialStateName: "Montserrat",
		NumericCode:       "500",
		InternetccTLD:     ".ms",
		Flag:              Flag_Montserrat,
	},
	{
		Alpha2Code:        "MA",
		CountryName:       "Morocco",
		OfficialStateName: "The Kingdom of Morocco",
		NumericCode:       "504",
		InternetccTLD:     ".ma",
		Flag:              Flag_Morocco,
	},
	{
		Alpha2Code:        "MZ",
		CountryName:       "Mozambique",
		OfficialStateName: "The Republic of Mozambique",
		NumericCode:       "508",
		InternetccTLD:     ".mz",
		Flag:              Flag_Mozambique,
	},
	{
		Alpha2Code:        "MM",
		CountryName:       "Myanmar",
		OfficialStateName: "The Republic of the Union of Myanmar",
		NumericCode:       "104",
		InternetccTLD:     ".mm",
		Flag:              Flag_Myanmar_Burma,
	},
	{
		Alpha2Code:        "NA",
		CountryName:       "Namibia",
		OfficialStateName: "The Republic of Namibia",
		NumericCode:       "516",
		InternetccTLD:     ".na",
		Flag:              Flag_Namibia,
	},
	{
		Alpha2Code:        "NR",
		CountryName:       "Nauru",
		OfficialStateName: "The Republic of Nauru",
		NumericCode:       "520",
		InternetccTLD:     ".nr",
		Flag:              Flag_Nauru,
	},
	{
		Alpha2Code:        "NP",
		CountryName:       "Nepal",
		OfficialStateName: "The Federal Democratic Republic of Nepal",
		NumericCode:       "524",
		InternetccTLD:     ".np",
		Flag:              Flag_Nepal,
	},
	{
		Alpha2Code:        "NL",
		CountryName:       "Netherlands (the)",
		OfficialStateName: "The Kingdom of the Netherlands",
		NumericCode:       "528",
		InternetccTLD:     ".nl",
		Flag:              Flag_Netherlands,
	},
	{
		Alpha2Code:        "NC",
		CountryName:       "New Caledonia",
		OfficialStateName: "New Caledonia",
		NumericCode:       "540",
		InternetccTLD:     ".nc",
		Flag:              Flag_New_Caledonia,
	},
	{
		Alpha2Code:        "NZ",
		CountryName:       "New Zealand",
		OfficialStateName: "New Zealand",
		NumericCode:       "554",
		InternetccTLD:     ".nz",
		Flag:              Flag_New_Zealand,
	},
	{
		Alpha2Code:        "NI",
		CountryName:       "Nicaragua",
		OfficialStateName: "The Republic of Nicaragua",
		NumericCode:       "558",
		InternetccTLD:     ".ni",
		Flag:              Flag_Nicaragua,
	},
	{
		Alpha2Code:        "NE",
		CountryName:       "Niger (the)",
		OfficialStateName: "The Republic of the Niger",
		NumericCode:       "562",
		InternetccTLD:     ".ne",
		Flag:              Flag_Niger,
	},
	{
		Alpha2Code:        "NG",
		CountryName:       "Nigeria",
		OfficialStateName: "The Federal Republic of Nigeria",
		NumericCode:       "566",
		InternetccTLD:     ".ng",
		Flag:              Flag_Nigeria,
	},
	{
		Alpha2Code:        "NU",
		CountryName:       "Niue",
		OfficialStateName: "Niue",
		NumericCode:       "570",
		InternetccTLD:     ".nu",
		Flag:              Flag_Niue,
	},
	{
		Alpha2Code:        "NF",
		CountryName:       "Norfolk Island",
		OfficialStateName: "The Territory of Norfolk Island",
		NumericCode:       "574",
		InternetccTLD:     ".nf",
		Flag:              Flag_Norfolk_Island,
	},
	{
		Alpha2Code:        "MP",
		CountryName:       "Northern Mariana Islands (the)",
		OfficialStateName: "The Commonwealth of the Northern Mariana Islands",
		NumericCode:       "580",
		InternetccTLD:     ".mp",
		Flag:              Flag_Northern_Mariana_Islands,
	},
	{
		Alpha2Code:        "NO",
		CountryName:       "Norway",
		OfficialStateName: "The Kingdom of Norway",
		NumericCode:       "578",
		InternetccTLD:     ".no",
		Flag:              Flag_Norway,
	},
	{
		Alpha2Code:        "OM",
		CountryName:       "Oman",
		OfficialStateName: "The Sultanate of Oman",
		NumericCode:       "512",
		InternetccTLD:     ".om",
		Flag:              Flag_Oman,
	},
	{
		Alpha2Code:        "PK",
		CountryName:       "Pakistan",
		OfficialStateName: "The Islamic Republic of Pakistan",
		NumericCode:       "586",
		InternetccTLD:     ".pk",
		Flag:              Flag_Pakistan,
	},
	{
		Alpha2Code:        "PW",
		CountryName:       "Palau",
		OfficialStateName: "The Republic of Palau",
		NumericCode:       "585",
		InternetccTLD:     ".pw",
		Flag:              Flag_Palau,
	},
	{
		Alpha2Code:        "PS",
		CountryName:       "Palestine, State of",
		OfficialStateName: "The State of Palestine",
		NumericCode:       "275",
		InternetccTLD:     ".ps",
		Flag:              Flag_Palestinian_Territories,
	},
	{
		Alpha2Code:        "PA",
		CountryName:       "Panama",
		OfficialStateName: "The Republic of Panamá",
		NumericCode:       "591",
		InternetccTLD:     ".pa",
		Flag:              Flag_Panama,
	},
	{
		Alpha2Code:        "PG",
		CountryName:       "Papua New Guinea",
		OfficialStateName: "The Independent State of Papua New Guinea",
		NumericCode:       "598",
		InternetccTLD:     ".pg",
		Flag:              Flag_Papua_New_Guinea,
	},
	{
		Alpha2Code:        "PY",
		CountryName:       "Paraguay",
		OfficialStateName: "The Republic of Paraguay",
		NumericCode:       "600",
		InternetccTLD:     ".py",
		Flag:              Flag_Paraguay,
	},
	{
		Alpha2Code:        "PE",
		CountryName:       "Peru",
		OfficialStateName: "The Republic of Perú",
		NumericCode:       "604",
		InternetccTLD:     ".pe",
		Flag:              Flag_Peru,
	},
	{
		Alpha2Code:        "PH",
		CountryName:       "Philippines (the)",
		OfficialStateName: "The Republic of the Philippines",
		NumericCode:       "608",
		InternetccTLD:     ".ph",
		Flag:              Flag_Philippines,
	},
	{
		Alpha2Code:        "PN",
		CountryName:       "Pitcairn Islands",
		OfficialStateName: "The Pitcairn, Henderson, Ducie and Oeno Islands",
		NumericCode:       "612",
		InternetccTLD:     ".pn",
		Flag:              Flag_Pitcairn_Islands,
	},
	{
		Alpha2Code:        "PL",
		CountryName:       "Poland",
		OfficialStateName: "The Republic of Poland",
		NumericCode:       "616",
		InternetccTLD:     ".pl",
		Flag:              Flag_Poland,
	},
	{
		Alpha2Code:        "PT",
		CountryName:       "Portugal",
		OfficialStateName: "The Portuguese Republic",
		NumericCode:       "620",
		InternetccTLD:     ".pt",
		Flag:              Flag_Portugal,
	},
	{
		Alpha2Code:        "PR",
		CountryName:       "Puerto Rico",
		OfficialStateName: "The Commonwealth of Puerto Rico",
		NumericCode:       "630",
		InternetccTLD:     ".pr",
		Flag:              Flag_Puerto_Rico,
	},
	{
		Alpha2Code:        "QA",
		CountryName:       "Qatar",
		OfficialStateName: "The State of Qatar",
		NumericCode:       "634",
		InternetccTLD:     ".qa",
		Flag:              Flag_Qatar,
	},
	{
		Alpha2Code:        "RE",
		CountryName:       "Réunion",
		OfficialStateName: "Réunion",
		NumericCode:       "638",
		InternetccTLD:     ".re",
		Flag:              Flag_Réunion,
	},
	{
		Alpha2Code:        "RO",
		CountryName:       "Romania",
		OfficialStateName: "Romania",
		NumericCode:       "642",
		InternetccTLD:     ".ro",
		Flag:              Flag_Romania,
	},
	{
		Alpha2Code:        "RU",
		CountryName:       "[w]",
		OfficialStateName: "The Russian Federation",
		NumericCode:       "643",
		InternetccTLD:     ".ru",
		Flag:              Flag_Russia,
	},
	{
		Alpha2Code:        "RW",
		CountryName:       "Rwanda",
		OfficialStateName: "The Republic of Rwanda",
		NumericCode:       "646",
		InternetccTLD:     ".rw",
		Flag:              Flag_Rwanda,
	},
	{
		Alpha2Code:        "BL",
		CountryName:       "Saint Barthélemy",
		OfficialStateName: "The Collectivity of Saint-Barthélemy",
		NumericCode:       "652",
		InternetccTLD:     ".bl",
		Flag:              Flag_StBarthélemy,
	},
	{
		Alpha2Code:        "SH",
		CountryName:       "Tristan da Cunha",
		OfficialStateName: "Saint Helena, Ascension and Tristan da Cunha",
		NumericCode:       "654",
		InternetccTLD:     ".sh",
		Flag:              Flag_Tristan_Da_Cunha,
	},
	{
		Alpha2Code:        "KN",
		CountryName:       "Saint Kitts and Nevis",
		OfficialStateName: "Saint Kitts and Nevis",
		NumericCode:       "659",
		InternetccTLD:     ".kn",
		Flag:              Flag_StKitts_Nevis,
	},
	{
		Alpha2Code:        "LC",
		CountryName:       "Saint Lucia",
		OfficialStateName: "Saint Lucia",
		NumericCode:       "662",
		InternetccTLD:     ".lc",
		Flag:              Flag_StLucia,
	},
	{
		Alpha2Code:        "MF",
		CountryName:       "Saint Martin (French part)",
		OfficialStateName: "The Collectivity of Saint-Martin",
		NumericCode:       "663",
		InternetccTLD:     ".mf",
		Flag:              Flag_StMartin,
	},
	{
		Alpha2Code:        "PM",
		CountryName:       "Saint Pierre and Miquelon",
		OfficialStateName: "The Overseas Collectivity of Saint-Pierre and Miquelon",
		NumericCode:       "666",
		InternetccTLD:     ".pm",
		Flag:              Flag_StPierre_Miquelon,
	},
	{
		Alpha2Code:        "VC",
		CountryName:       "Saint Vincent and the Grenadines",
		OfficialStateName: "Saint Vincent and the Grenadines",
		NumericCode:       "670",
		InternetccTLD:     ".vc",
		Flag:              Flag_StVincent_Grenadines,
	},
	{
		Alpha2Code:        "WS",
		CountryName:       "Samoa",
		OfficialStateName: "The Independent State of Samoa",
		NumericCode:       "882",
		InternetccTLD:     ".ws",
		Flag:              Flag_Samoa,
	},
	{
		Alpha2Code:        "SM",
		CountryName:       "San Marino",
		OfficialStateName: "The Republic of San Marino",
		NumericCode:       "674",
		InternetccTLD:     ".sm",
		Flag:              Flag_San_Marino,
	},
	{
		Alpha2Code:        "ST",
		CountryName:       "Sao Tome and Principe",
		OfficialStateName: "The Democratic Republic of São Tomé and Príncipe",
		NumericCode:       "678",
		InternetccTLD:     ".st",
		Flag:              Flag_São_Tomé_Príncipe,
	},
	{
		Alpha2Code:        "SA",
		CountryName:       "Saudi Arabia",
		OfficialStateName: "The Kingdom of Saudi Arabia",
		NumericCode:       "682",
		InternetccTLD:     ".sa",
		Flag:              Flag_Saudi_Arabia,
	},
	{
		Alpha2Code:        "SN",
		CountryName:       "Senegal",
		OfficialStateName: "The Republic of Senegal",
		NumericCode:       "686",
		InternetccTLD:     ".sn",
		Flag:              Flag_Senegal,
	},
	{
		Alpha2Code:        "RS",
		CountryName:       "Serbia",
		OfficialStateName: "The Republic of Serbia",
		NumericCode:       "688",
		InternetccTLD:     ".rs",
		Flag:              Flag_Serbia,
	},
	{
		Alpha2Code:        "SC",
		CountryName:       "Seychelles",
		OfficialStateName: "The Republic of Seychelles",
		NumericCode:       "690",
		InternetccTLD:     ".sc",
		Flag:              Flag_Seychelles,
	},
	{
		Alpha2Code:        "SL",
		CountryName:       "Sierra Leone",
		OfficialStateName: "The Republic of Sierra Leone",
		NumericCode:       "694",
		InternetccTLD:     ".sl",
		Flag:              Flag_Sierra_Leone,
	},
	{
		Alpha2Code:        "SG",
		CountryName:       "Singapore",
		OfficialStateName: "The Republic of Singapore",
		NumericCode:       "702",
		InternetccTLD:     ".sg",
		Flag:              Flag_Singapore,
	},
	{
		Alpha2Code:        "SX",
		CountryName:       "Sint Maarten (Dutch part)",
		OfficialStateName: "Sint Maarten",
		NumericCode:       "534",
		InternetccTLD:     ".sx",
		Flag:              Flag_Sint_Maarten,
	},
	{
		Alpha2Code:        "SK",
		CountryName:       "Slovakia",
		OfficialStateName: "The Slovak Republic",
		NumericCode:       "703",
		InternetccTLD:     ".sk",
		Flag:              Flag_Slovakia,
	},
	{
		Alpha2Code:        "SI",
		CountryName:       "Slovenia",
		OfficialStateName: "The Republic of Slovenia",
		NumericCode:       "705",
		InternetccTLD:     ".si",
		Flag:              Flag_Slovenia,
	},
	{
		Alpha2Code:        "SB",
		CountryName:       "Solomon Islands",
		OfficialStateName: "The Solomon Islands",
		NumericCode:       "090",
		InternetccTLD:     ".sb",
		Flag:              Flag_Solomon_Islands,
	},
	{
		Alpha2Code:        "SO",
		CountryName:       "Somalia",
		OfficialStateName: "The Federal Republic of Somalia",
		NumericCode:       "706",
		InternetccTLD:     ".so",
		Flag:              Flag_Somalia,
	},
	{
		Alpha2Code:        "ZA",
		CountryName:       "South Africa",
		OfficialStateName: "The Republic of South Africa",
		NumericCode:       "710",
		InternetccTLD:     ".za",
		Flag:              Flag_South_Africa,
	},
	{
		Alpha2Code:        "GS",
		CountryName:       "South Georgia and the South Sandwich Islands",
		OfficialStateName: "South Georgia and the South Sandwich Islands",
		NumericCode:       "239",
		InternetccTLD:     ".gs",
		Flag:              Flag_South_Georgia_South_Sandwich_Islands,
	},
	{
		Alpha2Code:        "SS",
		CountryName:       "South Sudan",
		OfficialStateName: "The Republic of South Sudan",
		NumericCode:       "728",
		InternetccTLD:     ".ss",
		Flag:              Flag_South_Sudan,
	},
	{
		Alpha2Code:        "ES",
		CountryName:       "Spain",
		OfficialStateName: "The Kingdom of Spain",
		NumericCode:       "724",
		InternetccTLD:     ".es",
		Flag:              Flag_Spain,
	},
	{
		Alpha2Code:        "LK",
		CountryName:       "Sri Lanka",
		OfficialStateName: "The Democratic Socialist Republic of Sri Lanka",
		NumericCode:       "144",
		InternetccTLD:     ".lk",
		Flag:              Flag_Sri_Lanka,
	},
	{
		Alpha2Code:        "SD",
		CountryName:       "Sudan (the)",
		OfficialStateName: "The Republic of the Sudan",
		NumericCode:       "729",
		InternetccTLD:     ".sd",
		Flag:              Flag_Sudan,
	},
	{
		Alpha2Code:        "SR",
		CountryName:       "Suriname",
		OfficialStateName: "The Republic of Suriname",
		NumericCode:       "740",
		InternetccTLD:     ".sr",
		Flag:              Flag_Suriname,
	},
	{
		Alpha2Code:        "SJ",
		CountryName:       "Jan Mayen",
		OfficialStateName: "Svalbard and Jan Mayen",
		NumericCode:       "744",
		InternetccTLD:     "[x]",
		Flag:              Flag_Svalbard_Jan_Mayen,
	},
	{
		Alpha2Code:        "SE",
		CountryName:       "Sweden",
		OfficialStateName: "The Kingdom of Sweden",
		NumericCode:       "752",
		InternetccTLD:     ".se",
		Flag:              Flag_Sweden,
	},
	{
		Alpha2Code:        "CH",
		CountryName:       "Switzerland",
		OfficialStateName: "The Swiss Confederation",
		NumericCode:       "756",
		InternetccTLD:     ".ch",
		Flag:              Flag_Switzerland,
	},
	{
		Alpha2Code:        "SY",
		CountryName:       "Syria",
		OfficialStateName: "The Syrian Arab Republic",
		NumericCode:       "760",
		InternetccTLD:     ".sy",
		Flag:              Flag_Syria,
	},
	{
		Alpha2Code:        "TW",
		CountryName:       "Taiwan",
		OfficialStateName: "The Republic of China",
		NumericCode:       "158",
		InternetccTLD:     ".tw",
		Flag:              Flag_Taiwan,
	},
	{
		Alpha2Code:        "TJ",
		CountryName:       "Tajikistan",
		OfficialStateName: "The Republic of Tajikistan",
		NumericCode:       "762",
		InternetccTLD:     ".tj",
		Flag:              Flag_Tajikistan,
	},
	{
		Alpha2Code:        "TZ",
		CountryName:       "Tanzania, the United Republic of",
		OfficialStateName: "The United Republic of Tanzania",
		NumericCode:       "834",
		InternetccTLD:     ".tz",
		Flag:              Flag_Tanzania,
	},
	{
		Alpha2Code:        "TH",
		CountryName:       "Thailand",
		OfficialStateName: "The Kingdom of Thailand",
		NumericCode:       "764",
		InternetccTLD:     ".th",
		Flag:              Flag_Thailand,
	},
	{
		Alpha2Code:        "TL",
		CountryName:       "East Timor",
		OfficialStateName: "The Democratic Republic of Timor-Leste",
		NumericCode:       "626",
		InternetccTLD:     ".tl",
		Flag:              Flag_Timor_Leste,
	},
	{
		Alpha2Code:        "TG",
		CountryName:       "Togo",
		OfficialStateName: "The Togolese Republic",
		NumericCode:       "768",
		InternetccTLD:     ".tg",
		Flag:              Flag_Togo,
	},
	{
		Alpha2Code:        "TK",
		CountryName:       "Tokelau",
		OfficialStateName: "Tokelau",
		NumericCode:       "772",
		InternetccTLD:     ".tk",
		Flag:              Flag_Tokelau,
	},
	{
		Alpha2Code:        "TO",
		CountryName:       "Tonga",
		OfficialStateName: "The Kingdom of Tonga",
		NumericCode:       "776",
		InternetccTLD:     ".to",
		Flag:              Flag_Tonga,
	},
	{
		Alpha2Code:        "TT",
		CountryName:       "Trinidad and Tobago",
		OfficialStateName: "The Republic of Trinidad and Tobago",
		NumericCode:       "780",
		InternetccTLD:     ".tt",
		Flag:              Flag_Trinidad_Tobago,
	},
	{
		Alpha2Code:        "TN",
		CountryName:       "Tunisia",
		OfficialStateName: "The Republic of Tunisia",
		NumericCode:       "788",
		InternetccTLD:     ".tn",
		Flag:              Flag_Tunisia,
	},
	{
		Alpha2Code:        "TR",
		CountryName:       "Turkey",
		OfficialStateName: "The Republic of Türkiye",
		NumericCode:       "792",
		InternetccTLD:     ".tr",
		Flag:              Flag_Turkey,
	},
	{
		Alpha2Code:        "TM",
		CountryName:       "Turkmenistan",
		OfficialStateName: "Turkmenistan",
		NumericCode:       "795",
		InternetccTLD:     ".tm",
		Flag:              Flag_Turkmenistan,
	},
	{
		Alpha2Code:        "TC",
		CountryName:       "Turks and Caicos Islands (the)",
		OfficialStateName: "The Turks and Caicos Islands",
		NumericCode:       "796",
		InternetccTLD:     ".tc",
		Flag:              Flag_Turks_Caicos_Islands,
	},
	{
		Alpha2Code:        "TV",
		CountryName:       "Tuvalu",
		OfficialStateName: "Tuvalu",
		NumericCode:       "798",
		InternetccTLD:     ".tv",
		Flag:              Flag_Tuvalu,
	},
	{
		Alpha2Code:        "UG",
		CountryName:       "Uganda",
		OfficialStateName: "The Republic of Uganda",
		NumericCode:       "800",
		InternetccTLD:     ".ug",
		Flag:              Flag_Uganda,
	},
	{
		Alpha2Code:        "UA",
		CountryName:       "Ukraine",
		OfficialStateName: "Ukraine",
		NumericCode:       "804",
		InternetccTLD:     ".ua",
		Flag:              Flag_Ukraine,
	},
	{
		Alpha2Code:        "AE",
		CountryName:       "United Arab Emirates (the)",
		OfficialStateName: "The United Arab Emirates",
		NumericCode:       "784",
		InternetccTLD:     ".ae",
		Flag:              Flag_United_Arab_Emirates,
	},
	{
		Alpha2Code:        "GB",
		CountryName:       "United Kingdom of Great Britain and Northern Ireland (the)",
		OfficialStateName: "The United Kingdom of Great Britain and Northern Ireland",
		NumericCode:       "826",
		InternetccTLD:     ".gb",
		Flag:              Flag_United_Kingdom,
	},
	{
		Alpha2Code:        "UM",           // Baker Island, formerly known as New Nantucket,
		CountryName:       "Baker Island", // is an uninhabited atoll just north of the Equator in the central Pacific Ocean
		OfficialStateName: "Baker Island", // ownership?
		NumericCode:       "581",
		InternetccTLD:     "[af]",
		Flag:              Flag_FIXME_TODO,
	},
	{
		Alpha2Code:        "US",
		CountryName:       "United States of America (the)",
		OfficialStateName: "The United States of America",
		NumericCode:       "840",
		InternetccTLD:     ".us",
		Flag:              Flag_United_States,
	},
	{
		Alpha2Code:        "UY",
		CountryName:       "Uruguay",
		OfficialStateName: "The Oriental Republic of Uruguay",
		NumericCode:       "858",
		InternetccTLD:     ".uy",
		Flag:              Flag_Uruguay,
	},
	{
		Alpha2Code:        "UZ",
		CountryName:       "Uzbekistan",
		OfficialStateName: "The Republic of Uzbekistan",
		NumericCode:       "860",
		InternetccTLD:     ".uz",
		Flag:              Flag_Uzbekistan,
	},
	{
		Alpha2Code:        "VU",
		CountryName:       "Vanuatu",
		OfficialStateName: "The Republic of Vanuatu",
		NumericCode:       "548",
		InternetccTLD:     ".vu",
		Flag:              Flag_Vanuatu,
	},
	{
		Alpha2Code:        "VE",
		CountryName:       "Venezuela (Bolivarian Republic of)",
		OfficialStateName: "The Bolivarian Republic of Venezuela",
		NumericCode:       "862",
		InternetccTLD:     ".ve",
		Flag:              Flag_Venezuela,
	},
	{
		Alpha2Code:        "VN",
		CountryName:       "Vietnam",
		OfficialStateName: "The Socialist Republic of Viet Nam",
		NumericCode:       "704",
		InternetccTLD:     ".vn",
		Flag:              Flag_Vietnam,
	},
	{
		Alpha2Code:        "VG",
		CountryName:       "British Virgin Islands",
		OfficialStateName: "The Virgin Islands",
		NumericCode:       "092",
		InternetccTLD:     ".vg",
		Flag:              Flag_British_Virgin_Islands,
	},
	{
		Alpha2Code:        "VI",
		CountryName:       "US Virgin Islands",
		OfficialStateName: "The Virgin Islands of the United States",
		NumericCode:       "850",
		InternetccTLD:     ".vi",
		Flag:              Flag_USVirgin_Islands,
	},
	{
		Alpha2Code:        "WF",
		CountryName:       "Wallis and Futuna",
		OfficialStateName: "The Territory of the Wallis and Futuna Islands",
		NumericCode:       "876",
		InternetccTLD:     ".wf",
		Flag:              Flag_Wallis_Futuna,
	},
	{
		Alpha2Code:        "EH",
		CountryName:       "Saharawi",
		OfficialStateName: "The Sahrawi Arab Democratic Republic",
		NumericCode:       "732",
		InternetccTLD:     "[al]",
		Flag:              Flag_Western_Sahara,
	},
	{
		Alpha2Code:        "YE",
		CountryName:       "Yemen",
		OfficialStateName: "The Republic of Yemen",
		NumericCode:       "887",
		InternetccTLD:     ".ye",
		Flag:              Flag_Yemen,
	},
	{
		Alpha2Code:        "ZM",
		CountryName:       "Zambia",
		OfficialStateName: "The Republic of Zambia",
		NumericCode:       "894",
		InternetccTLD:     ".zm",
		Flag:              Flag_Zambia,
	},
	{
		Alpha2Code:        "ZW",
		CountryName:       "Zimbabwe",
		OfficialStateName: "The Republic of Zimbabwe",
		NumericCode:       "716",
		InternetccTLD:     ".zw",
		Flag:              Flag_Zimbabwe,
	},
}
